export const clothes = [
  {
    clothes_aid: 1,
    clothes_title: "Box Tee Oat",
    clothes_category: "Tees & Tanks",
    clothes_price: "200",
    clothes_image: "na-card-a1.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 2,
    clothes_title: "Box tee Black",
    clothes_category: "Tees & Tanks",
    clothes_price: "2500",
    clothes_image: "shirt1.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 3,
    clothes_title: "Rugger Fleece Tee Grey",
    clothes_category: "Tees & Tanks",
    clothes_price: "4,150",
    clothes_image: "shirt2.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 4,
    clothes_title: "Tall Tee White",
    clothes_category: "Tees & Tanks",
    clothes_price: "500",
    clothes_image: "shirt3.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 4,
    clothes_title: "Tall Tee White",
    clothes_category: "Tees & Tanks",
    clothes_price: "2,580",
    clothes_image: "shirt3.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 4,
    clothes_title: "Tall Tee White",
    clothes_category: "Tees & Tanks",
    clothes_price: "9,500",
    clothes_image: "shirt3.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 4,
    clothes_title: "Denim Pants",
    clothes_category: "Pants",
    clothes_price: "3,500",
    clothes_image: "pants1.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 5,
    clothes_title: "Gray Jogger Pants",
    clothes_category: "Pants",
    clothes_price: "2,200",
    clothes_image: "pants2.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 6,
    clothes_title: "Brown Jogger Pants",
    clothes_category: "Pants",
    clothes_price: "2,900",
    clothes_image: "pants4.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 7,
    clothes_title: "Gray Hoddie Jacket",
    clothes_category: "Sweaters",
    clothes_price: "2,100",
    clothes_image: "jacket.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 8,
    clothes_title: "Printed Hoddie",
    clothes_category: "Sweaters",
    clothes_price: "2,530",
    clothes_image: "jacket1.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 8,
    clothes_title: "Cream Sweater",
    clothes_category: "Sweaters",
    clothes_price: "2,510",
    clothes_image: "jacket2.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 9,
    clothes_title: "Olive Sweater",
    clothes_category: "Sweaters",
    clothes_price: "5,210",
    clothes_image: "jacket3.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 10,
    clothes_title: "Black Sweater",
    clothes_category: "Sweaters",
    clothes_price: "5,240",
    clothes_image: "jacket4.jpg",
    clothes_is_active: true,
  },
  {
    clothes_aid: 11,
    clothes_title: "Army Green Hodie",
    clothes_category: "Sweaters",
    clothes_price: "9,240",
    clothes_image: "jacket5.jpg",
    clothes_is_active: true,
  },
];
