export const newArrivalArray = [
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "ALorem ipsum dolor sit amet",
    slug: "alorem-ipsum-dolor-sit-amet",
    price: "149.99",
    thumbnails: [
      "na-card-a1.jpg",
      "na-card-a2.jpg",
      "shirt2.jpg",
      "shirt3.jpg",
    ],
        sizes: [24, 37, 50, 43, 27],
        rating: 5,
    
  },
  {
    img1: "na-card-a2.jpg",
    img2: "na-card-a1.jpg",
    title: "BLorem ipsum dolor sit amet",
    slug: "blorem-ipsum-dolor-sit-amet",
    price: "1499.99",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [24, 37, 50, 43, 27],
    rating:4,
  },
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "CLorem ipsum dolor sit amet",
    slug: "clorem-ipsum-dolor-sit-amet",
    price: "1599.99",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [24, 37, 50, 43, 27],
    rating: 3,
  },
  {
    img1: "na-card-a2.jpg",
    img2: "na-card-a1.jpg",
    title: "DLorem ipsum dolor sit amet",
    slug: "dlorem-ipsum-dolor-sit-amet",
    price: "1699.99",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [24, 37, 50, 43, 27],
    rating: 2, 
  },
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "ELorem ipsum dolor sit amet",
    slug: "elorem-ipsum-dolor-sit-amet",
    price: "1799.99",
    thumbnails: ["na-card-a1.jpg", "na-card-a2.jpg"],
    sizes: [24, 37, 50, 43, 27],
    rating: 1,
  },
];
